services:
  partsnepal-api:
    image: ghcr.io/gauravyad69/partsnepal/partsnepal-api:latest
    container_name: partsnepal-api
    ports:
      - "9090:9090"  # Expose port 9090 from container to host
    environment:
      - JAVA_OPTS=-Xmx512m  # Optional: Adjust Java memory settings if needed
    restart: unless-stopped  # Automatically restart the container if it stops
    networks:
      - partsnepal-network
    deploy:
      resources:
        limits:
          memory: 750M  # Set memory limit
          cpus: "0.7"   # Limit to 70% of a CPU core
        reservations:
          memory: 512M  # Reserve at least 512MB
      update_config:
        parallelism: 1  # Update one container at a time
        delay: 10s      # Wait 10s between updates
        order: start-first  # Start a new container before stopping the old one

networks:
  partsnepal-network:
    driver: bridge

