name: Gradle Build and Deploy
on:
 push:
   branches: [ main ]
   paths:
     - 'API/partsnepal-api/**'  # Only trigger on changes in API directory
 pull_request:
   branches: [ main ]
   paths:
     - 'API/partsnepal-api/**'
jobs:
 build:
   runs-on: ubuntu-latest
   defaults:
     run:
       working-directory: ./API/partsnepal-api  # Set working directory for all run steps
    steps:
   - uses: actions/checkout@v3
   
   - name: Set up JDK
     uses: actions/setup-java@v3
     with:
       java-version: '17'
       distribution: 'temurin'
       
   - name: Build with Gradle
     uses: gradle/gradle-build-action@v2
     with:
       build-root-directory: API/partsnepal-api
       arguments: build
       
   - name: Create Release
     id: create_release
     uses: actions/create-release@v1
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
       tag_name: release-${{ github.sha }}
       release_name: Release ${{ github.sha }}
       draft: false
       prerelease: false
       
   - name: Upload Release Asset
     uses: actions/upload-release-asset@v1
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
       upload_url: ${{ steps.create_release.outputs.upload_url }}
       asset_path: ./API/partsnepal-api/build/libs/np.com.parts.api-all.jar
       asset_name: np.com.parts.api-all.jar
       asset_content_type: application/java-archive
