name: Run Gradle Build
'on':
  push:
    paths:
      - API/partsnepal-api/**
  pull_request:
    paths:
      - API/partsnepal-api/**
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: API/partsnepal-api
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
          build-scan-terms-of-use-agree: 'yes'
      - name: Execute Gradle build
        run: ./gradlew build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Package
          path: build/libs/*.jar
